# Generated by Django 5.2.14 on 2026-05-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auth_integration'),
    ]

    operations = [
        # 0004 で room フィールドを RemoveField した際に DB 上の unique_together 制約は
        # 実質消えているが、Django の移行状態に (room, username) が残ったままになっている。
        # DB には触れず state_operations のみで状態を空に同期する。
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='brushsettings',
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),
        # verbose_name='ID' を追加するだけの変更で DB スキーマに影響はない
        migrations.AlterField(
            model_name='userroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
